// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: v1/packetyeeter.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyzerService_StreamSignals_FullMethodName   = "/packetyeeter.v1.AnalyzerService/StreamSignals"
	AnalyzerService_LookupJA4H_FullMethodName      = "/packetyeeter.v1.AnalyzerService/LookupJA4H"
	AnalyzerService_LookupJA4T_FullMethodName      = "/packetyeeter.v1.AnalyzerService/LookupJA4T"
	AnalyzerService_VerifyBot_FullMethodName       = "/packetyeeter.v1.AnalyzerService/VerifyBot"
	AnalyzerService_VerifyAICrawler_FullMethodName = "/packetyeeter.v1.AnalyzerService/VerifyAICrawler"
	AnalyzerService_GetThreatIntel_FullMethodName  = "/packetyeeter.v1.AnalyzerService/GetThreatIntel"
	AnalyzerService_GetReputation_FullMethodName   = "/packetyeeter.v1.AnalyzerService/GetReputation"
	AnalyzerService_ReportBlock_FullMethodName     = "/packetyeeter.v1.AnalyzerService/ReportBlock"
	AnalyzerService_Health_FullMethodName          = "/packetyeeter.v1.AnalyzerService/Health"
)

// AnalyzerServiceClient is the client API for AnalyzerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AnalyzerService is the main service that the Collector connects to
// for sending signals and receiving commands.
type AnalyzerServiceClient interface {
	// Bidirectional streaming for real-time signal exchange
	StreamSignals(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Signal, Command], error)
	// Lookup JA4H fingerprint in the database
	LookupJA4H(ctx context.Context, in *JA4HLookupRequest, opts ...grpc.CallOption) (*JA4HLookupResponse, error)
	// Lookup JA4T fingerprint
	LookupJA4T(ctx context.Context, in *JA4TLookupRequest, opts ...grpc.CallOption) (*JA4TLookupResponse, error)
	// Verify if an IP/UA combination is a legitimate bot
	VerifyBot(ctx context.Context, in *BotVerifyRequest, opts ...grpc.CallOption) (*BotVerifyResponse, error)
	// Verify AI crawler (OpenAI, Anthropic, etc.)
	VerifyAICrawler(ctx context.Context, in *AICrawlerVerifyRequest, opts ...grpc.CallOption) (*AICrawlerVerifyResponse, error)
	// Get threat intelligence for an IP
	GetThreatIntel(ctx context.Context, in *ThreatIntelRequest, opts ...grpc.CallOption) (*ThreatIntelResponse, error)
	// Get reputation score for an entity
	GetReputation(ctx context.Context, in *ReputationRequest, opts ...grpc.CallOption) (*ReputationResponse, error)
	// Report blocked IP (for metrics/tracking)
	ReportBlock(ctx context.Context, in *BlockReport, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Health check
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type analyzerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyzerServiceClient(cc grpc.ClientConnInterface) AnalyzerServiceClient {
	return &analyzerServiceClient{cc}
}

func (c *analyzerServiceClient) StreamSignals(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Signal, Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnalyzerService_ServiceDesc.Streams[0], AnalyzerService_StreamSignals_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Signal, Command]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalyzerService_StreamSignalsClient = grpc.BidiStreamingClient[Signal, Command]

func (c *analyzerServiceClient) LookupJA4H(ctx context.Context, in *JA4HLookupRequest, opts ...grpc.CallOption) (*JA4HLookupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JA4HLookupResponse)
	err := c.cc.Invoke(ctx, AnalyzerService_LookupJA4H_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerServiceClient) LookupJA4T(ctx context.Context, in *JA4TLookupRequest, opts ...grpc.CallOption) (*JA4TLookupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JA4TLookupResponse)
	err := c.cc.Invoke(ctx, AnalyzerService_LookupJA4T_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerServiceClient) VerifyBot(ctx context.Context, in *BotVerifyRequest, opts ...grpc.CallOption) (*BotVerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotVerifyResponse)
	err := c.cc.Invoke(ctx, AnalyzerService_VerifyBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerServiceClient) VerifyAICrawler(ctx context.Context, in *AICrawlerVerifyRequest, opts ...grpc.CallOption) (*AICrawlerVerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AICrawlerVerifyResponse)
	err := c.cc.Invoke(ctx, AnalyzerService_VerifyAICrawler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerServiceClient) GetThreatIntel(ctx context.Context, in *ThreatIntelRequest, opts ...grpc.CallOption) (*ThreatIntelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThreatIntelResponse)
	err := c.cc.Invoke(ctx, AnalyzerService_GetThreatIntel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerServiceClient) GetReputation(ctx context.Context, in *ReputationRequest, opts ...grpc.CallOption) (*ReputationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReputationResponse)
	err := c.cc.Invoke(ctx, AnalyzerService_GetReputation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerServiceClient) ReportBlock(ctx context.Context, in *BlockReport, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AnalyzerService_ReportBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerServiceClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AnalyzerService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyzerServiceServer is the server API for AnalyzerService service.
// All implementations must embed UnimplementedAnalyzerServiceServer
// for forward compatibility.
//
// AnalyzerService is the main service that the Collector connects to
// for sending signals and receiving commands.
type AnalyzerServiceServer interface {
	// Bidirectional streaming for real-time signal exchange
	StreamSignals(grpc.BidiStreamingServer[Signal, Command]) error
	// Lookup JA4H fingerprint in the database
	LookupJA4H(context.Context, *JA4HLookupRequest) (*JA4HLookupResponse, error)
	// Lookup JA4T fingerprint
	LookupJA4T(context.Context, *JA4TLookupRequest) (*JA4TLookupResponse, error)
	// Verify if an IP/UA combination is a legitimate bot
	VerifyBot(context.Context, *BotVerifyRequest) (*BotVerifyResponse, error)
	// Verify AI crawler (OpenAI, Anthropic, etc.)
	VerifyAICrawler(context.Context, *AICrawlerVerifyRequest) (*AICrawlerVerifyResponse, error)
	// Get threat intelligence for an IP
	GetThreatIntel(context.Context, *ThreatIntelRequest) (*ThreatIntelResponse, error)
	// Get reputation score for an entity
	GetReputation(context.Context, *ReputationRequest) (*ReputationResponse, error)
	// Report blocked IP (for metrics/tracking)
	ReportBlock(context.Context, *BlockReport) (*emptypb.Empty, error)
	// Health check
	Health(context.Context, *emptypb.Empty) (*HealthResponse, error)
	mustEmbedUnimplementedAnalyzerServiceServer()
}

// UnimplementedAnalyzerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyzerServiceServer struct{}

func (UnimplementedAnalyzerServiceServer) StreamSignals(grpc.BidiStreamingServer[Signal, Command]) error {
	return status.Error(codes.Unimplemented, "method StreamSignals not implemented")
}
func (UnimplementedAnalyzerServiceServer) LookupJA4H(context.Context, *JA4HLookupRequest) (*JA4HLookupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupJA4H not implemented")
}
func (UnimplementedAnalyzerServiceServer) LookupJA4T(context.Context, *JA4TLookupRequest) (*JA4TLookupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupJA4T not implemented")
}
func (UnimplementedAnalyzerServiceServer) VerifyBot(context.Context, *BotVerifyRequest) (*BotVerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyBot not implemented")
}
func (UnimplementedAnalyzerServiceServer) VerifyAICrawler(context.Context, *AICrawlerVerifyRequest) (*AICrawlerVerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyAICrawler not implemented")
}
func (UnimplementedAnalyzerServiceServer) GetThreatIntel(context.Context, *ThreatIntelRequest) (*ThreatIntelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThreatIntel not implemented")
}
func (UnimplementedAnalyzerServiceServer) GetReputation(context.Context, *ReputationRequest) (*ReputationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReputation not implemented")
}
func (UnimplementedAnalyzerServiceServer) ReportBlock(context.Context, *BlockReport) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportBlock not implemented")
}
func (UnimplementedAnalyzerServiceServer) Health(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAnalyzerServiceServer) mustEmbedUnimplementedAnalyzerServiceServer() {}
func (UnimplementedAnalyzerServiceServer) testEmbeddedByValue()                         {}

// UnsafeAnalyzerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyzerServiceServer will
// result in compilation errors.
type UnsafeAnalyzerServiceServer interface {
	mustEmbedUnimplementedAnalyzerServiceServer()
}

func RegisterAnalyzerServiceServer(s grpc.ServiceRegistrar, srv AnalyzerServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyzerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyzerService_ServiceDesc, srv)
}

func _AnalyzerService_StreamSignals_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnalyzerServiceServer).StreamSignals(&grpc.GenericServerStream[Signal, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalyzerService_StreamSignalsServer = grpc.BidiStreamingServer[Signal, Command]

func _AnalyzerService_LookupJA4H_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JA4HLookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServiceServer).LookupJA4H(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyzerService_LookupJA4H_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServiceServer).LookupJA4H(ctx, req.(*JA4HLookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyzerService_LookupJA4T_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JA4TLookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServiceServer).LookupJA4T(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyzerService_LookupJA4T_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServiceServer).LookupJA4T(ctx, req.(*JA4TLookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyzerService_VerifyBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServiceServer).VerifyBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyzerService_VerifyBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServiceServer).VerifyBot(ctx, req.(*BotVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyzerService_VerifyAICrawler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AICrawlerVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServiceServer).VerifyAICrawler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyzerService_VerifyAICrawler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServiceServer).VerifyAICrawler(ctx, req.(*AICrawlerVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyzerService_GetThreatIntel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThreatIntelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServiceServer).GetThreatIntel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyzerService_GetThreatIntel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServiceServer).GetThreatIntel(ctx, req.(*ThreatIntelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyzerService_GetReputation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReputationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServiceServer).GetReputation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyzerService_GetReputation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServiceServer).GetReputation(ctx, req.(*ReputationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyzerService_ReportBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServiceServer).ReportBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyzerService_ReportBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServiceServer).ReportBlock(ctx, req.(*BlockReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyzerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyzerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServiceServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyzerService_ServiceDesc is the grpc.ServiceDesc for AnalyzerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyzerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "packetyeeter.v1.AnalyzerService",
	HandlerType: (*AnalyzerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LookupJA4H",
			Handler:    _AnalyzerService_LookupJA4H_Handler,
		},
		{
			MethodName: "LookupJA4T",
			Handler:    _AnalyzerService_LookupJA4T_Handler,
		},
		{
			MethodName: "VerifyBot",
			Handler:    _AnalyzerService_VerifyBot_Handler,
		},
		{
			MethodName: "VerifyAICrawler",
			Handler:    _AnalyzerService_VerifyAICrawler_Handler,
		},
		{
			MethodName: "GetThreatIntel",
			Handler:    _AnalyzerService_GetThreatIntel_Handler,
		},
		{
			MethodName: "GetReputation",
			Handler:    _AnalyzerService_GetReputation_Handler,
		},
		{
			MethodName: "ReportBlock",
			Handler:    _AnalyzerService_ReportBlock_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _AnalyzerService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSignals",
			Handler:       _AnalyzerService_StreamSignals_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "v1/packetyeeter.proto",
}

const (
	CollectorService_ExecuteCommand_FullMethodName = "/packetyeeter.v1.CollectorService/ExecuteCommand"
	CollectorService_GetStatus_FullMethodName      = "/packetyeeter.v1.CollectorService/GetStatus"
	CollectorService_Health_FullMethodName         = "/packetyeeter.v1.CollectorService/Health"
)

// CollectorServiceClient is the client API for CollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CollectorService allows the Analyzer to push commands to connected Collectors
type CollectorServiceClient interface {
	// Execute a blocking command
	ExecuteCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*CommandResult, error)
	// Get collector status
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CollectorStatus, error)
	// Health check
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type collectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorServiceClient(cc grpc.ClientConnInterface) CollectorServiceClient {
	return &collectorServiceClient{cc}
}

func (c *collectorServiceClient) ExecuteCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, CollectorService_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CollectorStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectorStatus)
	err := c.cc.Invoke(ctx, CollectorService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, CollectorService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectorServiceServer is the server API for CollectorService service.
// All implementations must embed UnimplementedCollectorServiceServer
// for forward compatibility.
//
// CollectorService allows the Analyzer to push commands to connected Collectors
type CollectorServiceServer interface {
	// Execute a blocking command
	ExecuteCommand(context.Context, *Command) (*CommandResult, error)
	// Get collector status
	GetStatus(context.Context, *emptypb.Empty) (*CollectorStatus, error)
	// Health check
	Health(context.Context, *emptypb.Empty) (*HealthResponse, error)
	mustEmbedUnimplementedCollectorServiceServer()
}

// UnimplementedCollectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollectorServiceServer struct{}

func (UnimplementedCollectorServiceServer) ExecuteCommand(context.Context, *Command) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedCollectorServiceServer) GetStatus(context.Context, *emptypb.Empty) (*CollectorStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedCollectorServiceServer) Health(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCollectorServiceServer) mustEmbedUnimplementedCollectorServiceServer() {}
func (UnimplementedCollectorServiceServer) testEmbeddedByValue()                          {}

// UnsafeCollectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectorServiceServer will
// result in compilation errors.
type UnsafeCollectorServiceServer interface {
	mustEmbedUnimplementedCollectorServiceServer()
}

func RegisterCollectorServiceServer(s grpc.ServiceRegistrar, srv CollectorServiceServer) {
	// If the following call panics, it indicates UnimplementedCollectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CollectorService_ServiceDesc, srv)
}

func _CollectorService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).ExecuteCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CollectorService_ServiceDesc is the grpc.ServiceDesc for CollectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "packetyeeter.v1.CollectorService",
	HandlerType: (*CollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommand",
			Handler:    _CollectorService_ExecuteCommand_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _CollectorService_GetStatus_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _CollectorService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/packetyeeter.proto",
}
