[packet-yeeter-agent]
spoe-agent packet-yeeter-agent
    messages packet-yeeter-metrics
    option var-prefix packetyeeter
    option continue-on-error
    use-backend spoe-packetyeeter
    timeout hello      1s
    timeout idle       2m
    timeout processing 1s
    log global

spoe-message packet-yeeter-metrics
    args src=src dst=var(txn.dst_ip) dst_port=var(txn.dst_port) status=status t_conn=var(sess.start_us) t_req=var(txn.req_us) method=var(txn.method) path=var(txn.path) host=var(txn.host) ua=var(txn.ua) accept=var(txn.accept) accept_language=var(txn.accept_language) accept_encoding=var(txn.accept_encoding) referer=var(txn.referer) has_cookies=var(txn.has_cookies) ja4=var(txn.fingerprint_ja4) ja4h=var(txn.fingerprint_ja4h) header_order=var(txn.header_order) sec_fetch_site=var(txn.sec_fetch_site) sec_fetch_mode=var(txn.sec_fetch_mode) sec_fetch_dest=var(txn.sec_fetch_dest) sec_fetch_user=var(txn.sec_fetch_user) tls_version=var(txn.tls_version) tls_cipher=var(txn.tls_cipher) conn_request_count=var(txn.conn_request_count)
    event on-http-response
    on-error ignore
    on-timeout ignore
